# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb81b565ebfdf988f9c8671db4eaab18a46156cc29ae3b45c11d4979d902abd1cb4595578154337fbc450bbf3819b5e372ba405e1e3f8a047089970966674ce2

test:
  secret_key_base: e1653298d0bb9ea2fb8ac5cbbb580700ad8d05504ea4c89ae0d6b046c1dfbc0ad325dc2345a0234d5c758e1af47d05cf82cf9973640674b98cf97db9cfbabfa9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
